--- #YAML:1.0
name: Email-Store-NamedEntity
version: 1.3
license: perl
distribution_type: module
requires:
  Email::Store: 0
  File::Slurp: 0
  Lingua::EN::NamedEntity: 0
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Email::Store::NamedEntity:
    file: lib/Email/Store/NamedEntity.pm
    version: 1.3
generated_by: Module::Build version 0.21
